### ISSUE TITLE
should the intro be behind the debug flag

### ISSUE THREAD

**Issue by ghost** [writeas/pherephone#2]
reading the comments at the beginning of `main` I wonder if the entrie header and intro text should be hidden behind the debugging flag as well.

**Comment by qwazix** [comment]
The header started being a line of `=` before being a header and I forgot to remove the comment above. I think an introductory text is good for someone who just runs the thing they downloaded. Maybe I could expand it a bit too.

I vote for removing the comment above and leaving the intro text always visible.

**Comment by ghost** [comment]
that works great for me too, it was the comment that made me wonder if it should be removed.
