### ISSUE TITLE
What is the license for this project?

### ISSUE THREAD

**Issue by strypey** [writeas/pherephone#6]
I've added this project to the ActivityPub watchlist on the fediverse.party wiki, but I can't seem to find any license information. It's helpful to put a file called "LICENSE" or "COPYING" into the repo, that explains the terms under which the source code can be reused.

**Comment by thebaer** [comment]
Thanks for mentioning this! It's AGPL -- just added [LICENSE](https://github.com/writeas/pherephone/blob/develop/LICENSE).

**Comment by strypey** [comment]
Matt Baer wrote:
> Thanks for mentioning this! It's AGPL

Thanks for the clarification, and for writing free code software :)
